### ISSUE TITLE
Possible error in convert_units formula

### ISSUE THREAD

**Issue by JoejynWan** [DistanceDevelopment/Distance#141]
Hi there, 

I am trying to conduct distance sampling with the `ds` function, and my data contains different units for my distance (meters), effort (kilometers), and area (hectares). In the documentation for `ds`, under the Units section, it states that : 

`Abundance for a survey region can be expressed as: A*N/a where A is Area for the survey region, N is the abundance in the covered (sampled) region, and a is the area of the sampled region and is in units of Effort * distance. The sampled region a is multiplied by convert_units, so it should be chosen such that the result is in the same units as Area. For example, if Effort was entered in kilometres, Area in hectares (100m x 100m) and distance in metres, then using convert_units=10 will convert a to units of hectares (100 to convert metres to 100 metres for distance and .1 to convert km to 100m units).`

However, when I try to use the `convert_units` function, it is giving me the wrong output (please see below image). I do think that it is meant to be 10 instead of 0.1, and that the error lies in `convert_unit`. 
![image](https://user-images.githubusercontent.com/65271133/199512805-a985faf4-3d2c-42ef-b225-95de20179a76.png)

The conversion units (cu) is currently calculated as `cu <- (du * eu)/au`, when I think it should be `cu <- au/(du * eu)`. 
![image](https://user-images.githubusercontent.com/65271133/199513431-b2bc4488-b219-433a-ba2e-c9d0bfe09e30.png)

Do let me know what you think, and if I am missing something. Thanks.

**Comment by erex** [comment]
@JoejynWan Let's walk through a simple example to see how the unit conversion should occur.

Given:
study area size (A) is expressed in hectares
transect length (L) is expressed in kilometers
perpendicular distances (d) to detections is measured in meters.

As the help page states, the area covered by our sampling (a) needs to be converted to the same units as used for the study area (A). What is the conversation factor?

The size of the covered area is total transect length multiplied by truncation distance (multiplied by 2 because we assume detections are made on both sides of the transect). Given the units of measure I stated above, units for the size of the covered region is kilometers times meters. If we express area of covered region in units of square meters, the measure is in thousands of square meters.

How many square meters in a hectare (the unit we are using to describe the size of A)? 10,000

The ratio of units of "a" over the units of "A" is 1000/10,000, making the conversion factor 0.1

**Comment by JoejynWan** [comment]
@erex Thank you so much for the quick reply. 

I am basing my understanding on the documentation for `ds`, whereby it states that "a is multiplied by convert_units, so it should be chosen such that the result is in the same units as Area". So taking your example, if a = 1000, and A = 10,000, then the conversion factor should be 10 so that a * 10 = 10,000 = A. 

If we are converting "A" to "a", then I would agree that the ratio of units of "a" over the units of "A" is 1000/10,000, making the conversion factor 0.1. However, I do believe that this is not the case?

**Comment by erex** [comment]
Step back and examine the situation more broadly.  There is a two order of magnitude difference between the conversion factor you believe to be appropriate (10) and the conversion factor computed by the function in question (0.1).

Applying the contrasting conversion factors to a data set will result in density or abundance estimates differing by a factor of 100. Many biologists know the size of the populations they are studying with sufficient insight to know if the estimates produced by the `Distance` package are incorrect by a factor of 100. We have not received reports from users that the population estimates are so badly mistaken. This "absence of evidence" argument suggests the computation using the conversion factor are  working as they should.

**Comment by lenthomas** [comment]
Thinking this can be closed now?

**Comment by erex** [comment]
received no response from my last comment. presume closing issue is acceptable to original poster
